server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
    location /farmacias {
        proxy_pass http://api_farmacias:8000/farmacias;
    }
    location /registrar {
        proxy_pass http://api_farmacias:8000/registrar;
    }
}
